
services:
  syncorbit:
    build: .
    container_name: syncorbit
    ports:
      - '5010:5010'
    volumes:
      - ./python:/app/python:rw # OPTIONAL in dev mode
      - /mnt/media/Media/Movies:/app/media:ro # your Unraid media
      - ./data:/app/data # persistent storage
    environment:
      - SYNCORBIT_DATA=/app/data
    restart: unless-stopped
